# Generated by Django 4.2.1 on 2024-05-27 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='tournamentobject',
            name='name',
            field=models.CharField(default='Мой турнир', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentobject',
            name='tournament_type',
            field=models.CharField(choices=[('SE', 'Олимпийская система'), ('DE', 'C двойным выбыванием')], default='SE', max_length=2),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
