# Generated by Django 4.2.1 on 2024-05-27 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tournament', '0002_usersettings_avatar_alter_tournamentobject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
