# Generated by Django 4.2.1 on 2024-05-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0003_remove_usersettings_avatar_alter_usersettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentobject',
            name='sport',
            field=models.CharField(choices=[('football', 'Футбол'), ('tennis', 'Теннис'), ('boxing', 'Бокс'), ('badminton', 'Бадминтон'), ('volleyball', 'Волейбол'), ('basketball', 'Баскетбол'), ('handball', 'Гандбол'), ('esports', 'Киберспорт'), ('hockey', 'Хоккей'), ('rugby', 'Регби')], default='football', max_length=20),
        ),
    ]
