# Generated by Django 4.2.1 on 2024-05-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0005_tournamentobject_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='Tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='Tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournament.tournamentobject'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'round', 'match_number')},
        ),
        migrations.RemoveField(
            model_name='match',
            name='description',
        ),
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
    ]
