# Generated by Django 4.2.1 on 2024-05-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0006_alter_match_unique_together_match_match_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tournamentobject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournamentobject',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='tournamentobject',
            name='start_date',
        ),
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='Tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='Tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Tournament.tournamentobject'),
        ),
        migrations.AlterField(
            model_name='tournamentobject',
            name='tournament_type',
            field=models.CharField(choices=[('SE', 'Олимпийская система'), ('DE', 'C двойным выбыванием')], default='SE', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'round')},
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_number',
        ),
    ]
