# Generated by Django 4.2.1 on 2024-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0008_tournamentobject_end_date_tournamentobject_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentobject',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournamentobject',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentobject',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
