# Generated by Django 4.2.1 on 2024-05-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0009_tournamentobject_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentobject',
            name='organizer',
            field=models.CharField(default='Организатор', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
