# Generated by Django 4.2.1 on 2024-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0011_match_result_team1_match_result_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentobject',
            name='map_center_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentobject',
            name='map_center_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentobject',
            name='map_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
