# Generated by Django 4.2.1 on 2024-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0013_alter_tournamentobject_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentobject',
            name='schedule_generated',
            field=models.BooleanField(default=False),
        ),
    ]
