# Generated by Django 4.2.1 on 2024-06-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organizer_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
