# Generated by Django 4.2.1 on 2024-06-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0017_remove_profile_organizer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentobject',
            name='public',
        ),
    ]
