# Generated by Django 4.2.1 on 2024-06-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0019_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournament.tournamentobject'),
        ),
    ]
