# Generated by Django 4.2.1 on 2024-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0021_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentobject',
            name='winner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
