# Generated by Django 4.2.1 on 2024-06-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0025_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'В ожидании'), ('A', 'Принято'), ('R', 'Отклонено')], default='P', max_length=1),
        ),
    ]
