# Generated by Django 4.2.1 on 2024-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0028_alter_application_team_alter_match_result_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentobject',
            name='rules_document',
            field=models.FileField(blank=True, null=True, upload_to='rules/'),
        ),
    ]
