# Generated by Django 4.2.1 on 2024-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0029_tournamentobject_rules_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentobject',
            name='tournament_type',
            field=models.CharField(choices=[('SE', 'Олимпийская система'), ('DE', 'С двойным выбыванием'), ('RR', 'Круговой турнир')], default='SE', max_length=2),
        ),
    ]
