# Generated by Django 4.2.1 on 2024-06-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0030_alter_tournamentobject_tournament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentobject',
            name='organizer',
        ),
    ]
