# Generated by Django 4.2.1 on 2024-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0031_remove_tournamentobject_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
