# Generated by Django 4.2.1 on 2024-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0034_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
